config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated do
   root :to => 'jobs#index', as: :authenticated
  end

  root to: 'jobs#homepage'

  resources "jobs"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord

  validates :url, :presence => true
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  has_many :jobs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :authenticate_user!, :except => [:homepage]
  protect_from_forgery except: :create


  def homepage
    render 'homepage'
  end

  def index
    @index = true
    @jobs = Job.where(user_id: current_user.id) unless current_user.blank?
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(jobs_params)
		@job.user_id = current_user.id
		if @job.save
			redirect_to '/jobs'
		else
			render 'new'
		end
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
   @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update(jobs_params)
    redirect_to "/jobs/#{@job.id}"
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:notice] = 'Job deleted successfully'
    redirect_to '/jobs'
  end

  def jobs_params
   params.require(:job).permit(:url, :position, :company, :rating, :status, :location, :info, :current_user)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb
<div class="jumbotron col-md-4 col-md-offset-4">
  <div class"col-sm-2 control-label">
    <%= form_for @job do |f| %>
      <div class="field">
        <%= f.label :url, class: "col-sm-3 control-label"  %>
        <%= f.url_field :url, class: "col-sm-6", required: true %><br>
      </div>

      <div class="field">
        <%= f.label :position, class: "col-sm-3 control-label" %>
        <%= f.text_field :position, class: "col-sm-6" %><br>
      </div>

      <div class="field">
        <%= f.label :company, class: "col-sm-3 control-label"  %>
        <%= f.text_field :company, class: "col-sm-6" %><br>
      </div>

      <div class="field">
        <%= f.label :location, class: "col-sm-3 control-label"  %>
        <%= f.text_field :location, class: "col-sm-6" %><br>
      </div>

      <div class="field">
        <%= f.label :rating, class: "col-sm-3 control-label"  %>
        <%= f.select :rating, [1,2,3,4,5]%><br>
      </div>

      <div class="field">
        <%= f.label :status, class: "col-sm-3 control-label"  %>
        <%= f.select :status, ["Interested","Applied", "Interview", "Rejected"]%><br>
      </div>

      <div class="field">
        <%= f.label :info, 'More info', class: "col-sm-3 control-label" %>
        <%= f.text_field :info, class: "col-sm-6"%><br>
      </div>
      <%= f.hidden_field :user_id, value: current_user.id %><br>
      <%= f.submit 'Update Job', class: "col-md-4"%>
    <% end %>
</div>

app/views/jobs/homepage.html.erb
<div class="jumbotron vertical-center">
  <h1 class="text-center">Welcome to Jobs Tracker</h1>
</div>
<div class="horizontal-center">
  <h2 class="text-center">Forget about excel spreadsheets to keep track of your job applications.<br>
    Create an account or sign in to get started!</h2>
</div>

app/views/jobs/index.html.erb
<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.6/dt-1.10.12/r-2.1.0/datatables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.1.0/js/dataTables.responsive.min.js"></script>

<script>

var table_id = null;
document.addEventListener("turbolinks:load", function() {
    table_id = $("#table_id").DataTable({
      responsive: {
          details: {
              type: 'column',
              target: 'tr'
          }
      },
      columnDefs: [ {
          className: 'control',
          orderable: false,
          targets: 0
      } ],
      deferRender: true,
      order: [ 1, 'asc' ],
        "createdRow": function ( row, data, index ) {
            if ( data[6] === 'Applied' ) {
                $('td', row).eq(6).addClass('applied');
            } else if (data[6] === 'Interview') {
                $('td', row).eq(6).addClass('interview');
            } else if (data[6] === 'Rejected') {
                $('td', row).eq(6).addClass('rejected');
            }
        },
        "bDestroy": true,
        "bSortClasses": false,
        "pageLength": 50
    } );
});

document.addEventListener("turbolinks:before-cache", function() {
  if ($("#table_id_wrapper").length === 1) {
    table_id.destroy();
  }
});


</script>


<table id="table_id" class="table table-striped table-bordered dt-responsive nowrap">
  <thead>
      <tr>
          <th></th>
          <th>Job position</th>
          <th>Company</th>
          <th>URL</th>
          <th>Location</th>
          <th>Rating</th>
          <th>Status</th>
          <th class="none">More info</th>
      </tr>
  </thead>
  <tbody>
    <tr>
    <% if current_user %>
    <% if @jobs.any? %>
      <% @jobs.each do |job| %>
          <td></td>
          <td><%= link_to job.position, job_path(job) %></td>
          <td><%= job.company%></td>
          <td><a href="<%=job.url%>">visit</td>
          <td><%= job.location%></td>
          <td><%= job.rating%></td>
          <td><%= job.status%></td>
          <td class="none"><%= job.info %></td>
        </tr>
      <% end %>
    <% else %>
      No jobs yet
    <% end %>
    <% end %>
  </tbody>
  </table>

app/views/jobs/new.html.erb
<div class="jumbotron col-md-4 col-md-offset-4">
  <div class"col-sm-2 control-label">
    <%= form_for @job do |f| %>
      <div class="field">
        <%= f.label :url, class: "col-sm-3 control-label"  %>
        <%= f.url_field :url, class: "col-sm-6", required: true %><br>
      </div>

      <div class="field">
        <%= f.label :position, class: "col-sm-3 control-label" %>
        <%= f.text_field :position, class: "col-sm-6" %><br>
      </div>

      <div class="field">
        <%= f.label :company, class: "col-sm-3 control-label"  %>
        <%= f.text_field :company, class: "col-sm-6" %><br>
      </div>

      <div class="field">
        <%= f.label :location, class: "col-sm-3 control-label"  %>
        <%= f.text_field :location, class: "col-sm-6" %><br>
      </div>

      <div class="field">
        <%= f.label :rating, class: "col-sm-3 control-label"  %>
        <%= f.select :rating, [1,2,3,4,5]%><br>
      </div>

      <div class="field">
        <%= f.label :status, class: "col-sm-3 control-label"  %>
        <%= f.select :status, ["Interested","Applied", "Interview", "Rejected"]%><br>
      </div>

      <div class="field">
        <%= f.label :info, 'More info', class: "col-sm-3 control-label"  %>
        <%= f.text_field :info, class: "col-sm-6"%><br>
      </div>
      <%= f.hidden_field :user_id, value: current_user.id %><br>
      <%= f.submit 'Add Job', class: "col-md-4"%>
    <% end %>
  </div>

app/views/jobs/show.html.erb
<div class="jumbotron col-md-4 col-md-offset-4">
  <h2><%= @job.position %> </h2>
  <p>@<%= @job.company %> </p>
  <p><strong>url: </strong><a href="<%=@job.url%>"><%=@job.url%></a></p>
  <p><strong>Location:</strong> <%= @job.location %> </p>
  <p><strong>Your own rating (out of 5) </strong><%= @job.rating %> </p>
  <p><strong>Status: </strong><%= @job.status %> </p>
  <p><%= @job.info %> </p>
  <%= link_to "Edit #{@job.position}", edit_job_path(@job) %>
  <%= link_to "Delete", job_path(@job), method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <div class="navbar-header">
    <%= link_to('Jobs Tracker', root_path, class: "navbar-brand", data: { turbolinks: false }) %>
  </div>
<div class="nav navbar-nav navbar-right">
<% if user_signed_in? %>
  <ul class="nav navbar-nav">
    <li><%= link_to 'Add a job', new_job_path%></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
<% else %>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
  </ul>
<% end %>
</div>
</nav>
<% if notice %>
<div><%= notice %></div>
<% end %>
<% if alert %>
<div><%= alert %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-cache">
    <title>Jobstracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= @index ? '' : 'background' %>">
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>